/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generadorcontraseña;

import javax.swing.ImageIcon;

/**
 *
 * @author Geny
 */
public class Pantalla extends javax.swing.JFrame {
    Gen generador;
    
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        setTitle("Generador de contraseñas");
        setSize(670, 469);
        pack();
        setLocationRelativeTo(null);
        //setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("/img/icono.png")).getImage());
        campoPassword.setBackground(new java.awt.Color(0,0,0,1));
        tamPasswd.setBackground(new java.awt.Color(0,0,0,1));
        generador = new Gen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tamPasswd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        checkNums = new javax.swing.JCheckBox();
        checkMayus = new javax.swing.JCheckBox();
        checkSim = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        campoPassword = new javax.swing.JTextField();
        checkMinus = new javax.swing.JCheckBox();
        btnGenerar = new javax.swing.JButton();
        btnCopiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tamPasswd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tamPasswd.setForeground(new java.awt.Color(255, 255, 255));
        tamPasswd.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tamPasswd.setText("9999999");
        tamPasswd.setAutoscrolls(false);
        tamPasswd.setBorder(null);
        tamPasswd.setCaretColor(new java.awt.Color(204, 255, 255));
        tamPasswd.setOpaque(false);
        getContentPane().add(tamPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 311, 100, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDec.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDec-hover.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnDec-clic.png"))); // NOI18N
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 336, 48, 37));

        checkNums.setSelected(true);
        checkNums.setContentAreaFilled(false);
        checkNums.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-deselected.png"))); // NOI18N
        checkNums.setRolloverEnabled(false);
        checkNums.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-selected.png"))); // NOI18N
        getContentPane().add(checkNums, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 342, 100, 30));

        checkMayus.setSelected(true);
        checkMayus.setContentAreaFilled(false);
        checkMayus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        checkMayus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-deselected.png"))); // NOI18N
        checkMayus.setRolloverEnabled(false);
        checkMayus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-selected.png"))); // NOI18N
        getContentPane().add(checkMayus, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 302, 120, 30));

        checkSim.setSelected(true);
        checkSim.setContentAreaFilled(false);
        checkSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-deselected.png"))); // NOI18N
        checkSim.setRolloverEnabled(false);
        checkSim.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-selected.png"))); // NOI18N
        getContentPane().add(checkSim, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 342, 110, 30));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnInc.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnInc-hover.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnInc-clic.png"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 300, 48, 37));

        campoPassword.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        campoPassword.setForeground(new java.awt.Color(255, 255, 255));
        campoPassword.setText("jTextField1");
        campoPassword.setBorder(null);
        campoPassword.setCaretColor(new java.awt.Color(204, 255, 255));
        campoPassword.setOpaque(false);
        campoPassword.setSelectionColor(new java.awt.Color(0, 2, 72));
        getContentPane().add(campoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 132, 310, 50));

        checkMinus.setSelected(true);
        checkMinus.setContentAreaFilled(false);
        checkMinus.setFocusPainted(false);
        checkMinus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-deselected.png"))); // NOI18N
        checkMinus.setRequestFocusEnabled(false);
        checkMinus.setRolloverEnabled(false);
        checkMinus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/checkbox-selected.png"))); // NOI18N
        getContentPane().add(checkMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 302, 110, 30));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGen.png"))); // NOI18N
        btnGenerar.setToolTipText("Generar nueva contraseña");
        btnGenerar.setBorderPainted(false);
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGenerar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGen-clic.png"))); // NOI18N
        btnGenerar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnGen-hover.png"))); // NOI18N
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 131, 54, 53));

        btnCopiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCopiar.png"))); // NOI18N
        btnCopiar.setToolTipText("Copiar la contraseña");
        btnCopiar.setBorderPainted(false);
        btnCopiar.setContentAreaFilled(false);
        btnCopiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCopiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCopiar-clic.png"))); // NOI18N
        btnCopiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btnCopiar-hover.png"))); // NOI18N
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCopiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 130, 54, 53));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setMaximumSize(null);
        jLabel1.setMinimumSize(null);
        jLabel1.setPreferredSize(new java.awt.Dimension(670, 468));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 468));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopiarActionPerformed
        campoPassword.selectAll();
        campoPassword.copy();
    }//GEN-LAST:event_btnCopiarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        generador.definirPropiedades(Integer.parseInt(tamPasswd.getText()),checkMinus.isSelected(),checkMayus.isSelected(),checkNums.isSelected(),checkSim.isSelected());
        campoPassword.setText(generador.generarClave());
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopiar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JTextField campoPassword;
    private javax.swing.JCheckBox checkMayus;
    private javax.swing.JCheckBox checkMinus;
    private javax.swing.JCheckBox checkNums;
    private javax.swing.JCheckBox checkSim;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tamPasswd;
    // End of variables declaration//GEN-END:variables
}
